# 1.DataSet Processing

In [1]:
import json
import os
import pandas as pd
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def load_from_json(filepath):
    """ Load a dictionary from a JSON file. """
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    return data

def save_to_json(filepath, data):
    """ Save a dictionary to a JSON file. """
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

def preprocess_text(text):
    """Preprocesses text by lowercasing, tokenizing, removing stopwords and stemming."""
    tokens = word_tokenize(text.lower())

    #TODO: numbers in claims and evidence may be useful, use isanum() instead of isalpha()?
    # filtered_tokens = [stemmer.stem(word) for word in tokens if word.isalpha() and word not in stop_words]
    filtered_tokens = [stemmer.stem(word) for word in tokens if word.isalnum() and word not in stop_words]
    return " ".join(filtered_tokens)

In [3]:
EVIDENCE_FILE = 'data/evidence.json'
TRAIN_FILE = 'data/train-claims.json'

evidence_data = load_from_json(EVIDENCE_FILE)
claims_data = load_from_json(TRAIN_FILE)

In [6]:
# # Map evidence IDs to their texts
# evidence_map = {eid: preprocess_text(text) for eid, text in evidence_data.items()}

# # Check whether directory already exists
# path = 'data/curated'
# if not os.path.exists(path):
#   os.mkdir(path)

# # Save preprocessed evidence file
# save_to_json(path + '/processed_evidence_map.json', evidence_map)

In [4]:
evidence_map = load_from_json('data/curated/processed_evidence_map.json')
evidence_df = pd.DataFrame(evidence_map.items(), columns=['id', 'evidence'])
evidence_df

                       id                                           evidence
0              evidence-0  john bennet law english entrepreneur agricultu...
1              evidence-1  lindberg began profession career age 16 eventu...
2              evidence-2                boston ladi cambridg vampir weekend
3              evidence-3  gerald franci goyer born octob 20 1936 profess...
4              evidence-4  detect abnorm oxytocinerg function schizoaffec...
...                   ...                                                ...
1208822  evidence-1208822                also properti contribut garag apart
1208823  evidence-1208823                       class fn org fyrd 6110 volda
1208824  evidence-1208824           dragon storm game game collect card game
1208825  evidence-1208825  state zeriuani great realm tradit relat tribe ...
1208826  evidence-1208826  storylin revolv around giant plesiosaur akin l...

[1208827 rows x 2 columns]

In [5]:
data_for_dataframe = []
for claim_id, claim_details in claims_data.items():
    claim_text = preprocess_text(claim_details['claim_text'])
    eids = claim_details['evidences']
    data_for_dataframe.append({
            'claim': claim_text,
            'evidence': eids
        })
    
# Create DataFrame
claims_df = pd.DataFrame(data_for_dataframe)
claims_df

,claim,evidence
0,scientif evid co2 pollut higher co2 concentr a...,"[evidence-442946, evidence-1194317, evidence-1..."
1,el niño drove record high global temperatur su...,"[evidence-338219, evidence-1127398]"
2,1946 pdo switch cool phase,"[evidence-530063, evidence-984887]"
3,weather channel john coleman provid evid convi...,"[evidence-1177431, evidence-782448, evidence-5..."
4,januari 2008 cap 12 month period global temper...,"[evidence-1010750, evidence-91661, evidence-72..."
...,...,...
1223,climat scientist say aspect case hurrican harv...,"[evidence-1055682, evidence-1047356, evidence-..."
1224,5th assess report 2013 ipcc estim human emiss ...,[evidence-916755]
1225,sinc mid 1970 global temperatur warm around de...,"[evidence-403673, evidence-889933, evidence-11..."
1226,abnorm temperatur spike februari earlier month...,"[evidence-97375, evidence-562427, evidence-521..."
1227,send oscil microwav antenna insid vacuum elect...,"[evidence-971105, evidence-457769, evidence-29..."

In [9]:
import random

# Vectorization
vectorizer = TfidfVectorizer()
all_texts = claims_df['claim'].tolist() + evidence_df['evidence'].tolist()

# sample_texts = random.sample(all_texts, 500)

# # Fit the vectorizer on both claims and evidences
# vectorizer.fit(sample_texts) 
# claim_vec = vectorizer.transform(claims_df['claim']).toarray() 
# claims_df['claim_tfidf'] = list(claim_vec) 
# claim_vec.shape

In [10]:

# evidence_vec = vectorizer.transform(evidence_df['evidence']).toarray()
# evidence_vec.shape

In [6]:
from gensim.models import Word2Vec
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# # We need data for training the model
# processed_sentences = [sent.split() for sent in all_texts]

# model = Word2Vec(
#     sentences=processed_sentences,
# )


tagged_data = [TaggedDocument(words=_d.split(), tags=[str(i)]) for i, _d in enumerate(all_texts)]
tagged_data[:1]

NameError: name 'all_texts' is not defined

In [12]:
model = Doc2Vec(vector_size=50, min_count=1, epochs=20)
  
model.build_vocab(tagged_data)
model.train(tagged_data, total_examples=model.corpus_count, epochs=model.epochs)
model.save("d2v.model")

In [13]:
model= Doc2Vec.load("d2v.model")

In [14]:
claims_df["vector"] = ""
for i in range(claims_df.shape[0]):
    inferred_vector = model.infer_vector(claims_df["claim"][i].split())
    claims_df["vector"][i] = inferred_vector
claims_df.to_csv('train_claim_vector.csv', index=False)
claims_df

,claim,evidence,vector
0,scientif evid co2 pollut higher co2 concentr a...,"[evidence-442946, evidence-1194317, evidence-1...","[0.0146728605, 0.12625784, -0.11276962, -0.072..."
1,el niño drove record high global temperatur su...,"[evidence-338219, evidence-1127398]","[0.09453631, -0.11059547, -0.14010006, -0.3389..."
2,1946 pdo switch cool phase,"[evidence-530063, evidence-984887]","[0.02883816, 0.06266779, -0.062135715, -0.0004..."
3,weather channel john coleman provid evid convi...,"[evidence-1177431, evidence-782448, evidence-5...","[0.07255763, -0.06587273, -0.10453821, 0.21353..."
4,januari 2008 cap 12 month period global temper...,"[evidence-1010750, evidence-91661, evidence-72...","[0.14178367, 0.014683072, 0.07192291, -0.22664..."
...,...,...,...
1223,climat scientist say aspect case hurrican harv...,"[evidence-1055682, evidence-1047356, evidence-...","[0.087618195, 0.0039493246, -0.283926, -0.1802..."
1224,5th assess report 2013 ipcc estim human emiss ...,[evidence-916755],"[0.05541971, 0.0630518, -0.014345324, -0.10453..."
1225,sinc mid 1970 global temperatur warm around de...,"[evidence-403673, evidence-889933, evidence-11...","[0.060415942, -0.00991549, -0.31236076, -0.121..."
1226,abnorm temperatur spike februari earlier month...,"[evidence-97375, evidence-562427, evidence-521...","[0.028433701, 0.06975459, -0.24209118, -0.2778..."
1227,send oscil microwav antenna insid vacuum elect...,"[evidence-971105, evidence-457769, evidence-29...","[0.00315044, 0.23906751, -0.12954646, -0.03514..."

In [15]:
evidence_df["vector"] = ""
for i in range(evidence_df.shape[0]):
    inferred_vector = model.infer_vector(evidence_df["evidence"][i].split())
    evidence_df["vector"][i] = inferred_vector
evidence_df

,id,evidence,vector
0,evidence-0,john bennet law english entrepreneur agricultu...,"[-0.10274349, -0.1521901, -0.14389612, -0.0647..."
1,evidence-1,lindberg began profession career age 16 eventu...,"[0.021682115, 0.09412701, -0.4038611, 0.014506..."
2,evidence-2,boston ladi cambridg vampir weekend,"[0.02425811, -0.04849113, 0.2777055, 0.0504023..."
3,evidence-3,gerald franci goyer born octob 20 1936 profess...,"[0.06251363, -0.26637015, -0.27424705, -0.1641..."
4,evidence-4,detect abnorm oxytocinerg function schizoaffec...,"[0.18131626, -0.11180243, -0.36687618, 0.10807..."
...,...,...,...
1208822,evidence-1208822,also properti contribut garag apart,"[0.044391014, -0.061329443, -0.169598, -0.0482..."
1208823,evidence-1208823,class fn org fyrd 6110 volda,"[0.039497066, -0.12655985, -0.3452346, -0.0604..."
1208824,evidence-1208824,dragon storm game game collect card game,"[0.00019951402, -0.16171727, -0.5241022, -0.10..."
1208825,evidence-1208825,state zeriuani great realm tradit relat tribe ...,"[0.17121354, -0.10472176, -0.53138727, 0.01106..."
1208826,evidence-1208826,storylin revolv around giant plesiosaur akin l...,"[0.26234785, 0.17921914, 0.09841553, 0.1471039..."

In [16]:
evidence_df.to_csv('evidence_vector.csv', index=False)

In [17]:
inferred_vector = model.infer_vector(tagged_data[0].words)
model.dv.most_similar([inferred_vector], topn=len(model.dv))

[('0', 0.8491038680076599),
 ('486870', 0.6858229637145996),
 ('505508', 0.6741513609886169),
 ('456801', 0.6693487763404846),
 ('253701', 0.6561805009841919),
 ('676209', 0.6514226198196411),
 ('791783', 0.6494963765144348),
 ('1022742', 0.6482139229774475),
 ('669420', 0.6476085186004639),
 ('782485', 0.6354619860649109),
 ('487135', 0.633489191532135),
 ('772661', 0.6323564052581787),
 ('110256', 0.6323369145393372),
 ('237548', 0.6318098902702332),
 ('836650', 0.6294390559196472),
 ('173293', 0.626121461391449),
 ('962769', 0.6254141926765442),
 ('1164705', 0.6250473260879517),
 ('936017', 0.6227185130119324),
 ('368255', 0.6211792230606079),
 ('532083', 0.6210688948631287),
 ('492540', 0.6207088232040405),
 ('16838', 0.6194145083427429),
 ('199208', 0.6190609931945801),
 ('890627', 0.6188330054283142),
 ('956128', 0.6175991892814636),
 ('383086', 0.6174643635749817),
 ('675489', 0.6173979640007019),
 ('914341', 0.6150795817375183),
 ('1166851', 0.6134316325187683),
 ('202507', 0.6125044226646423),
 ('979873', 0.6118085384368896),
 ('626232', 0.6103485822677612),
 ('1019735', 0.607848048210144),
 ('923789', 0.6077272891998291),
 ('17415', 0.6075593829154968),
 ('1171254', 0.6068112850189209),
 ('416458', 0.6062968373298645),
 ('343922', 0.6060530543327332),
 ('581176', 0.6057140827178955),
 ('20241', 0.6048225164413452),
 ('418373', 0.6043707132339478),
 ('739990', 0.6042354702949524),
 ('1150458', 0.6041308641433716),
 ('927', 0.6032572984695435),
 ('538025', 0.6027141809463501),
 ('167344', 0.6022385358810425),
 ('319616', 0.6012730598449707),
 ('746593', 0.6010892391204834),
 ('1039422', 0.6008474230766296),
 ('1119890', 0.6007799506187439),
 ('714182', 0.600424587726593),
 ('809438', 0.5992842316627502),
 ('576182', 0.5986166000366211),
 ('475888', 0.5981249213218689),
 ('403444', 0.5978823900222778),
 ('225463', 0.5978476405143738),
 ('687876', 0.597788393497467),
 ('68553', 0.5969784259796143),
 ('146305', 0.5966663956642151),
 ('682256', 0.5960394740104675),
 ('17731', 0.5955970287322998),
 ('506967', 0.5955431461334229),
 ('803263', 0.5953590273857117),
 ('1163459', 0.5953252911567688),
 ('592748', 0.5952695608139038),
 ('93152', 0.5947406888008118),
 ('853', 0.5946646928787231),
 ('502146', 0.5937222242355347),
 ('807312', 0.5936663150787354),
 ('1106590', 0.5936193466186523),
 ('845184', 0.593340277671814),
 ('405211', 0.5932533740997314),
 ('1043292', 0.5932502746582031),
 ('374635', 0.5929687023162842),
 ('457244', 0.5928844213485718),
 ('205845', 0.5923296213150024),
 ('85027', 0.591623067855835),
 ('843070', 0.5903686881065369),
 ('1155971', 0.5897043347358704),
 ('14308', 0.5896847248077393),
 ('30362', 0.5895557999610901),
 ('628240', 0.5893487930297852),
 ('874173', 0.589318037033081),
 ('929024', 0.588978111743927),
 ('643129', 0.5887534618377686),
 ('553561', 0.5886677503585815),
 ('694374', 0.5885014533996582),
 ('1172750', 0.5884158611297607),
 ('688601', 0.588086724281311),
 ('545304', 0.5880095362663269),
 ('131720', 0.5873687267303467),
 ('1184353', 0.5871669054031372),
 ('655038', 0.5871554613113403),
 ('527905', 0.5870786905288696),
 ('562530', 0.5867204070091248),
 ('738509', 0.5864561796188354),
 ('474512', 0.5864195227622986),
 ('1152045', 0.5860821604728699),
 ('452101', 0.5860152244567871),
 ('1090276', 0.585110604763031),
 ('822410', 0.5850868821144104),
 ('1150269', 0.5849295854568481),
 ('1052307', 0.5839824676513672),
 ('44467', 0.5838738083839417),
 ('555093', 0.5835254788398743),
 ('282322', 0.5833321213722229),
 ('699454', 0.5831405520439148),
 ('473132', 0.5828421711921692),
 ('408232', 0.582067608833313),
 ('939599', 0.5818598866462708),
 ('796134', 0.5815480351448059),
 ('304875', 0.5803881287574768),
 ('1142638', 0.5798130035400391),
 ('313997', 0.5798078775405884),
 ('170251', 0.5796436667442322),
 ('1014029', 0.5795643925666809),
 ('756863', 0.5795555710792542),
 ('184890', 0.5795096755027771),
 ('852794', 0.5790418982505798),
 ('487894', 0.5788523554801941),
 ('677235', 0.5784227848052979),
 ('84584', 0.5777221322059631),
 ('771458', 0.5777139067649841),
 ('385502', 0.5774646997451782),
 ('690863', 0.5773248076438904),
 ('838258', 0.5772011876106262),
 ('228123', 0.5770800709724426),
 ('887634', 0.5769005417823792),
 ('52804', 0.5761104822158813),
 ('379935', 0.5758049488067627),
 ('1172248', 0.5757639408111572),
 ('150027', 0.5754514336585999),
 ('907489', 0.5753005743026733),
 ('591757', 0.5750695466995239),
 ('677616', 0.5737535357475281),
 ('341227', 0.5735393166542053),
 ('1095934', 0.5734468102455139),
 ('736473', 0.57344651222229),
 ('853758', 0.5729880928993225),
 ('983611', 0.5729255676269531),
 ('561699', 0.5727459192276001),
 ('417417', 0.5719122886657715),
 ('839730', 0.5715979337692261),
 ('1063990', 0.5712295770645142),
 ('1104036', 0.5710523128509521),
 ('607806', 0.5709518194198608),
 ('833588', 0.5706862807273865),
 ('1188', 0.5703086853027344),
 ('409802', 0.5702163577079773),
 ('1175657', 0.5700517296791077),
 ('1148115', 0.5693607330322266),
 ('65316', 0.5687888860702515),
 ('253084', 0.5687341094017029),
 ('418350', 0.5685694217681885),
 ('1184625', 0.5685262084007263),
 ('208573', 0.5684171319007874),
 ('700059', 0.5683859586715698),
 ('168374', 0.567363977432251),
 ('447858', 0.5670823454856873),
 ('945933', 0.5669747591018677),
 ('835001', 0.5668491721153259),
 ('832798', 0.5667665600776672),
 ('965407', 0.5666941404342651),
 ('249280', 0.5663597583770752),
 ('87704', 0.5663182735443115),
 ('309953', 0.5663158893585205),
 ('99679', 0.5661791563034058),
 ('1043265', 0.5661203861236572),
 ('978192', 0.5660818219184875),
 ('770959', 0.5658454895019531),
 ('782877', 0.5658267736434937),
 ('232677', 0.5655557513237),
 ('177854', 0.5654622316360474),
 ('987529', 0.5652482509613037),
 ('244302', 0.5650832653045654),
 ('180066', 0.5647193789482117),
 ('885011', 0.5643500089645386),
 ('1207869', 0.5642467737197876),
 ('238653', 0.5634797215461731),
 ('618126', 0.5626481175422668),
 ('726903', 0.5625906586647034),
 ('122152', 0.5625479221343994),
 ('603241', 0.5623283982276917),
 ('239549', 0.5622754693031311),
 ('955531', 0.5622435808181763),
 ('1113759', 0.5621865391731262),
 ('534485', 0.5621863007545471),
 ('798807', 0.5621200203895569),
 ('600326', 0.5620675683021545),
 ('207016', 0.5615299344062805),
 ('1187408', 0.5614880919456482),
 ('216435', 0.5613890290260315),
 ('439773', 0.5610900521278381),
 ('313459', 0.5610299110412598),
 ('85838', 0.5610233545303345),
 ('64666', 0.560982346534729),
 ('849734', 0.5607056617736816),
 ('1092361', 0.560677707195282),
 ('934496', 0.5603431463241577),
 ('342081', 0.560015082359314),
 ('203360', 0.5597109794616699),
 ('5855', 0.5596383810043335),
 ('1184299', 0.5595255494117737),
 ('1030665', 0.5595128536224365),
 ('490789', 0.5594375133514404),
 ('1146580', 0.5590654015541077),
 ('330703', 0.5589353442192078),
 ('447889', 0.5588617324829102),
 ('1092550', 0.558768093585968),
 ('427875', 0.5587428212165833),
 ('510889', 0.5584976077079773),
 ('1151717', 0.5584955811500549),
 ('384525', 0.5584878325462341),
 ('614837', 0.5580600500106812),
 ('1017705', 0.5579820871353149),
 ('322947', 0.5578141212463379),
 ('676322', 0.5576384663581848),
 ('839744', 0.5576197504997253),
 ('465069', 0.5573258996009827),
 ('1041914', 0.5572819709777832),
 ('489483', 0.5572653412818909),
 ('419596', 0.5572199821472168),
 ('708523', 0.5571157932281494),
 ('522237', 0.5570089221000671),
 ('1180839', 0.556922197341919),
 ('1182809', 0.5568560361862183),
 ('946929', 0.5566430687904358),
 ('241143', 0.5563937425613403),
 ('346449', 0.5562446713447571),
 ('116955', 0.5562403798103333),
 ('453831', 0.5562021136283875),
 ('411', 0.5561850070953369),
 ('137607', 0.5561355352401733),
 ('1033121', 0.555969774723053),
 ('1043602', 0.5556401610374451),
 ('1132355', 0.555436909198761),
 ('95297', 0.5552985072135925),
 ('805266', 0.5552560687065125),
 ('147302', 0.5551879405975342),
 ('671', 0.5551720857620239),
 ('1075751', 0.5550772547721863),
 ('794508', 0.5550574064254761),
 ('1061353', 0.55502849817276),
 ('572096', 0.554398238658905),
 ('3704', 0.5543711185455322),
 ('804659', 0.554216742515564),
 ('240896', 0.5540928244590759),
 ('1131070', 0.5537806749343872),
 ('962691', 0.5533570647239685),
 ('350144', 0.5532448291778564),
 ('900912', 0.5530117154121399),
 ('157344', 0.552845299243927),
 ('877352', 0.5526818037033081),
 ('658578', 0.5523816347122192),
 ('1115279', 0.552333652973175),
 ('545901', 0.5518922805786133),
 ('860960', 0.5518656969070435),
 ('40254', 0.551861584186554),
 ('884576', 0.5518350601196289),
 ('794710', 0.5517292618751526),
 ('770697', 0.5516073107719421),
 ('757385', 0.5515221953392029),
 ('162965', 0.5513424873352051),
 ('1134651', 0.551286518573761),
 ('656292', 0.5511114001274109),
 ('378179', 0.5510153770446777),
 ('649353', 0.5508021116256714),
 ('366416', 0.5507982969284058),
 ('680675', 0.5507980585098267),
 ('975736', 0.5507479310035706),
 ('1156697', 0.5506693124771118),
 ('1015009', 0.5501785278320312),
 ('401569', 0.5501348376274109),
 ('668396', 0.5500402450561523),
 ('795504', 0.549993097782135),
 ('321031', 0.5497415661811829),
 ('631803', 0.5495367050170898),
 ('1147978', 0.5493937730789185),
 ('645613', 0.5490555763244629),
 ('665153', 0.5489371418952942),
 ('58089', 0.5489160418510437),
 ('901735', 0.5486538410186768),
 ('1144663', 0.5485578179359436),
 ('155778', 0.5485537052154541),
 ('286713', 0.5484045147895813),
 ('15303', 0.5483205318450928),
 ('162115', 0.5481887459754944),
 ('814019', 0.5481876134872437),
 ('732222', 0.5477262735366821),
 ('106069', 0.547492265701294),
 ('290478', 0.5474039912223816),
 ('239206', 0.5474022030830383),
 ('1050825', 0.5471909642219543),
 ('1187325', 0.5471823811531067),
 ('396273', 0.5470579862594604),
 ('392411', 0.5469405651092529),
 ('866731', 0.5469000935554504),
 ('184607', 0.5464739203453064),
 ('434452', 0.5463062524795532),
 ('939689', 0.5461969971656799),
 ('958683', 0.5460768938064575),
 ('951830', 0.5460343956947327),
 ('824900', 0.5459427237510681),
 ('273491', 0.5457651615142822),
 ('75902', 0.5457341074943542),
 ('121508', 0.5455251932144165),
 ('1137545', 0.5454788208007812),
 ('824708', 0.5451987981796265),
 ('240218', 0.5451546907424927),
 ('103744', 0.5450562238693237),
 ('1101887', 0.5448464751243591),
 ('568623', 0.544844925403595),
 ('183075', 0.5448245406150818),
 ('1107886', 0.5448216199874878),
 ('935359', 0.5447844862937927),
 ('590275', 0.5447577834129333),
 ('683004', 0.5447574257850647),
 ('527007', 0.5446330308914185),
 ('645452', 0.5445778369903564),
 ('638689', 0.544567346572876),
 ('1119705', 0.5445205569267273),
 ('959038', 0.5444766283035278),
 ('196507', 0.5444311499595642),
 ('925103', 0.5441482663154602),
 ('226474', 0.5441142916679382),
 ('1079815', 0.5440533757209778),
 ('301610', 0.5440515279769897),
 ('483098', 0.5440380573272705),
 ('258919', 0.543782651424408),
 ('77172', 0.5437055230140686),
 ('1040897', 0.5436291098594666),
 ('751809', 0.5436180233955383),
 ('485293', 0.5435429215431213),
 ('909199', 0.5433088541030884),
 ('564838', 0.543290376663208),
 ('1203881', 0.5431551337242126),
 ('379660', 0.5430774092674255),
 ('342701', 0.5429648160934448),
 ('18752', 0.5428113341331482),
 ('726042', 0.5428007245063782),
 ('288915', 0.5427354574203491),
 ('511089', 0.5426532030105591),
 ('259137', 0.5426226854324341),
 ('176318', 0.5425982475280762),
 ('22231', 0.5425946116447449),
 ('521165', 0.5423887968063354),
 ('288739', 0.5419327616691589),
 ('530472', 0.5418131351470947),
 ('572185', 0.5418094396591187),
 ('865498', 0.5417707562446594),
 ('616964', 0.5416114330291748),
 ('15731', 0.5415346622467041),
 ('414686', 0.5413752794265747),
 ('469303', 0.5413002967834473),
 ('940368', 0.5410996675491333),
 ('209318', 0.5407958626747131),
 ('131375', 0.5405569076538086),
 ('51752', 0.5405284762382507),
 ('844567', 0.5405224561691284),
 ('349193', 0.5404282808303833),
 ('315613', 0.5402042269706726),
 ('578842', 0.5401526689529419),
 ('124002', 0.5400455594062805),
 ('1034033', 0.5400093793869019),
 ('104275', 0.5399964451789856),
 ('273531', 0.5399758815765381),
 ('1052436', 0.539846658706665),
 ('272323', 0.5398375988006592),
 ('80659', 0.539660632610321),
 ('414758', 0.5396043062210083),
 ('750158', 0.5395464897155762),
 ('632770', 0.5394636988639832),
 ('137686', 0.5391757488250732),
 ('468273', 0.5388482809066772),
 ('1102513', 0.5387041568756104),
 ('947555', 0.5385566353797913),
 ('622019', 0.5384577512741089),
 ('371690', 0.5383473634719849),
 ('1135766', 0.5382797718048096),
 ('344400', 0.5381637215614319),
 ('44295', 0.5381457209587097),
 ('1194185', 0.5381332039833069),
 ('638278', 0.5380047559738159),
 ('780654', 0.5379661321640015),
 ('1136513', 0.5378653407096863),
 ('643802', 0.5378479957580566),
 ('227722', 0.5378238558769226),
 ('598212', 0.5376085638999939),
 ('911571', 0.5375857353210449),
 ('758781', 0.5373944044113159),
 ('783732', 0.537367582321167),
 ('792711', 0.5373644232749939),
 ('1181246', 0.5371907353401184),
 ('117420', 0.5370082855224609),
 ('851924', 0.5369971394538879),
 ('529297', 0.5369262099266052),
 ('812054', 0.5368502736091614),
 ('847820', 0.5368310809135437),
 ('76822', 0.536734402179718),
 ('308067', 0.5366429090499878),
 ('800546', 0.5364744067192078),
 ('194229', 0.536187469959259),
 ('427060', 0.5361416935920715),
 ('335520', 0.5359358787536621),
 ('635132', 0.535889744758606),
 ('613702', 0.5358671545982361),
 ('853584', 0.5358269214630127),
 ('270984', 0.5357083082199097),
 ('127096', 0.5356711149215698),
 ('171131', 0.535601019859314),
 ('95657', 0.5355629324913025),
 ('709109', 0.5355579853057861),
 ('221607', 0.5353100299835205),
 ('502106', 0.5352253913879395),
 ('253395', 0.5351575613021851),
 ('472236', 0.5350787043571472),
 ('376911', 0.5350109338760376),
 ('302832', 0.5349590182304382),
 ('91154', 0.5349016189575195),
 ('933847', 0.534839391708374),
 ('1086592', 0.5347681641578674),
 ('110376', 0.5347543954849243),
 ('909530', 0.5346881151199341),
 ('83331', 0.5345639586448669),
 ('801373', 0.5344006419181824),
 ('800442', 0.5342464447021484),
 ('165657', 0.5340456962585449),
 ('274369', 0.5340210795402527),
 ('314241', 0.5340005159378052),
 ('896098', 0.5339980721473694),
 ('666018', 0.5339509844779968),
 ('315412', 0.5339086651802063),
 ('427993', 0.5338478088378906),
 ('895212', 0.5338410139083862),
 ('674039', 0.5337859392166138),
 ('1185832', 0.5337290167808533),
 ('902418', 0.5336350798606873),
 ('192986', 0.5336090922355652),
 ('333291', 0.5335711240768433),
 ('1154456', 0.5335440039634705),
 ('676956', 0.5335313677787781),
 ('582327', 0.5333345532417297),
 ('334', 0.5333326458930969),
 ('681080', 0.5329592227935791),
 ('1115251', 0.5329495072364807),
 ('1168056', 0.5329180359840393),
 ('240005', 0.5328251719474792),
 ('215897', 0.5327644944190979),
 ('381561', 0.5326855778694153),
 ('1025536', 0.5324341654777527),
 ('129849', 0.5324016213417053),
 ('333877', 0.5323086977005005),
 ('621093', 0.5319658517837524),
 ('896864', 0.5318392515182495),
 ('938352', 0.5318223237991333),
 ('316068', 0.5318208336830139),
 ('979722', 0.531819224357605),
 ('867772', 0.5318158268928528),
 ('989365', 0.5317764282226562),
 ('73718', 0.5316800475120544),
 ('7407', 0.5315890908241272),
 ('403758', 0.5314005613327026),
 ('979528', 0.5313130021095276),
 ('44909', 0.5312429666519165),
 ('862162', 0.5312168002128601),
 ('325866', 0.531208336353302),
 ('159633', 0.531073272228241),
 ('570071', 0.531049907207489),
 ('976095', 0.5309622287750244),
 ('429', 0.5308250784873962),
 ('893844', 0.5307871699333191),
 ('694019', 0.5306941270828247),
 ('364430', 0.5305889844894409),
 ('1130200', 0.530511200428009),
 ('947623', 0.5304339528083801),
 ('716760', 0.5304252505302429),
 ('645059', 0.5301070213317871),
 ('871621', 0.5299935340881348),
 ('993230', 0.5299676656723022),
 ('430059', 0.5299361348152161),
 ('271829', 0.5299155116081238),
 ('638834', 0.5299153923988342),
 ('831378', 0.5298824310302734),
 ('244146', 0.5298655033111572),
 ('141548', 0.5297781229019165),
 ('1161364', 0.5296250581741333),
 ('190358', 0.5295510292053223),
 ('552921', 0.5295451879501343),
 ('342411', 0.5295060873031616),
 ('717125', 0.5294343829154968),
 ('979735', 0.529284656047821),
 ('1041370', 0.5292635560035706),
 ('802774', 0.5292245745658875),
 ('965646', 0.5291552543640137),
 ('678850', 0.5291200876235962),
 ('351093', 0.5290108323097229),
 ('568771', 0.5289517641067505),
 ('421570', 0.5288923978805542),
 ('735363', 0.5288633108139038),
 ('80445', 0.5288313031196594),
 ('916854', 0.5285755395889282),
 ('635011', 0.5285735130310059),
 ('666658', 0.5285180807113647),
 ('921200', 0.5283028483390808),
 ('500492', 0.5282835364341736),
 ('585887', 0.5282254219055176),
 ('518224', 0.5282158255577087),
 ('1183127', 0.5282126069068909),
 ('433168', 0.5281645655632019),
 ('1037672', 0.5279916524887085),
 ('953545', 0.5279701948165894),
 ('858232', 0.5279207825660706),
 ('283788', 0.5278753638267517),
 ('608699', 0.5277564525604248),
 ('434286', 0.5276177525520325),
 ('502283', 0.5275540947914124),
 ('1110506', 0.5274907350540161),
 ('251746', 0.5274752974510193),
 ('407777', 0.5274350643157959),
 ('456230', 0.5274126529693604),
 ('208787', 0.5273787975311279),
 ('98578', 0.5270646810531616),
 ('325204', 0.5270437598228455),
 ('939140', 0.527025580406189),
 ('297677', 0.5269578695297241),
 ('158020', 0.5269193649291992),
 ('706735', 0.5268900990486145),
 ('365396', 0.5268771648406982),
 ('138112', 0.5268493890762329),
 ('462121', 0.5267876386642456),
 ('973825', 0.5267869234085083),
 ('776873', 0.5267345309257507),
 ('209136', 0.5266855955123901),
 ('1060475', 0.5266358852386475),
 ('449164', 0.5263639688491821),
 ('56872', 0.5263485908508301),
 ('924434', 0.5263465046882629),
 ('9843', 0.5262364149093628),
 ('395932', 0.5262106657028198),
 ('250421', 0.5261372923851013),
 ('270891', 0.5260127186775208),
 ('279007', 0.5259096026420593),
 ('917151', 0.5258609056472778),
 ('36702', 0.5257545113563538),
 ('874581', 0.5257471203804016),
 ('986028', 0.5257026553153992),
 ('486679', 0.5256872773170471),
 ('658561', 0.5256237983703613),
 ('441735', 0.5255865454673767),
 ('866075', 0.5255653262138367),
 ('847397', 0.5255172252655029),
 ('169137', 0.5254794955253601),
 ('341330', 0.5254677534103394),
 ('587164', 0.5253498554229736),
 ('779006', 0.5251486897468567),
 ('335252', 0.5250892043113708),
 ('1076926', 0.5250815749168396),
 ('173517', 0.5247916579246521),
 ('734101', 0.5247425436973572),
 ('401440', 0.5246915817260742),
 ('414017', 0.5246779918670654),
 ('1028726', 0.5246410369873047),
 ('314780', 0.524580717086792),
 ('956327', 0.5245112776756287),
 ('389631', 0.5244770050048828),
 ('738329', 0.5244477391242981),
 ('32617', 0.5244418978691101),
 ('355350', 0.5243961811065674),
 ('932565', 0.524354100227356),
 ('644077', 0.5243421792984009),
 ('110004', 0.5243397951126099),
 ('895305', 0.5243231058120728),
 ('77040', 0.5242612957954407),
 ('27542', 0.5242274403572083),
 ('140871', 0.524188220500946),
 ('176165', 0.5240966081619263),
 ('452055', 0.5240720510482788),
 ('166835', 0.5240471959114075),
 ('923260', 0.5240160226821899),
 ('438010', 0.5239915251731873),
 ('759428', 0.5239579677581787),
 ('907615', 0.5239545702934265),
 ('536045', 0.523934543132782),
 ('437138', 0.5239132642745972),
 ('128723', 0.5238684415817261),
 ('427319', 0.5238274335861206),
 ('179203', 0.5238145589828491),
 ('204188', 0.523737907409668),
 ('601655', 0.523709237575531),
 ('413940', 0.5236843824386597),
 ('489380', 0.5236741304397583),
 ('323315', 0.5235967636108398),
 ('849308', 0.5235518217086792),
 ('232886', 0.5234904885292053),
 ('806861', 0.5234846472740173),
 ('209909', 0.5234771370887756),
 ('526500', 0.523423969745636),
 ('278284', 0.5234121680259705),
 ('327972', 0.5234010219573975),
 ('766379', 0.5233833193778992),
 ('220761', 0.5232975482940674),
 ('147022', 0.5232385396957397),
 ('769285', 0.5232234001159668),
 ('1019961', 0.52305668592453),
 ('703375', 0.522960901260376),
 ('439945', 0.5229313373565674),

In [18]:
from gensim.models import KeyedVectors
model.save("word2vec.model")
word_vectors = model.wv
word_vectors.save("word2vec.wordvectors")

# Load back with memory-mapping = read-only, shared across processes.
wv = KeyedVectors.load("word2vec.wordvectors", mmap='r')

In [19]:
DEV_FILE = 'data/dev-claims.json'
dev_claims_data = load_from_json(DEV_FILE)

data_for_dataframe = []
for claim_id, claim_details in dev_claims_data.items():
    claim_text = preprocess_text(claim_details['claim_text'])
    eids = claim_details['evidences']
    data_for_dataframe.append({
            'claim': claim_text,
            'evidence': eids
        })
    
# Create DataFrame
dev_claims_df = pd.DataFrame(data_for_dataframe)
dev_claims_df

,claim,evidence
0,south australia expens electr world,"[evidence-67732, evidence-572512]"
1,3 per cent total annual global emiss carbon di...,"[evidence-996421, evidence-1080858, evidence-2..."
2,mean world 1c warmer time,"[evidence-889933, evidence-694262]"
3,happen zika may also good model second worri e...,"[evidence-422399, evidence-702226, evidence-28..."
4,greenland lost tini fraction ice mass,"[evidence-52981, evidence-264761, evidence-947..."
...,...,...
149,suddenli label co2 pollut disservic ga play en...,"[evidence-409365, evidence-127519, evidence-85..."
150,natur orbit driven warm atmospher carbon dioxi...,"[evidence-368192, evidence-261690, evidence-20..."
151,mani world coral reef alreadi barren state con...,"[evidence-1124018, evidence-995813, evidence-1..."
152,recent studi led lawrenc livermor nation labor...,[evidence-660755]
153,coral may save mani creatur attempt move towar...,"[evidence-242575, evidence-1175280]"

In [20]:
dev_claims_df["vector"] = ""
for i in range(dev_claims_df.shape[0]):
    inferred_vector = model.infer_vector(dev_claims_df["claim"][i].split())
    dev_claims_df["vector"][i] = inferred_vector

dev_claims_df

,claim,evidence,vector
0,south australia expens electr world,"[evidence-67732, evidence-572512]","[-0.14695428, -0.09042706, -0.07665651, -0.079..."
1,3 per cent total annual global emiss carbon di...,"[evidence-996421, evidence-1080858, evidence-2...","[-0.112900116, -0.06112025, -0.2725012, -0.117..."
2,mean world 1c warmer time,"[evidence-889933, evidence-694262]","[0.03736557, -0.19243436, -0.17334826, -0.0584..."
3,happen zika may also good model second worri e...,"[evidence-422399, evidence-702226, evidence-28...","[-0.09359704, 0.12776884, -0.0056210617, 0.047..."
4,greenland lost tini fraction ice mass,"[evidence-52981, evidence-264761, evidence-947...","[0.0400215, -0.029097028, -0.2028753, -0.06434..."
...,...,...,...
149,suddenli label co2 pollut disservic ga play en...,"[evidence-409365, evidence-127519, evidence-85...","[0.28616574, 0.08560463, -0.035217457, -0.0863..."
150,natur orbit driven warm atmospher carbon dioxi...,"[evidence-368192, evidence-261690, evidence-20...","[0.01725103, 0.021944348, -0.07149153, 0.07700..."
151,mani world coral reef alreadi barren state con...,"[evidence-1124018, evidence-995813, evidence-1...","[-0.080627546, 0.10826158, -0.06843386, -0.110..."
152,recent studi led lawrenc livermor nation labor...,[evidence-660755],"[0.29741588, 0.2778654, -0.24676636, -0.173328..."
153,coral may save mani creatur attempt move towar...,"[evidence-242575, evidence-1175280]","[-0.032083467, -0.09604142, -0.19775431, 0.016..."

In [21]:
dev_claims_df['vector'].to_numpy()[0]

array([-0.14695428, -0.09042706, -0.07665651, -0.07978963,  0.12622364,
        0.00501365, -0.09204441, -0.01515245,  0.0946954 ,  0.09834569,
       -0.02270767, -0.07921322,  0.16500655, -0.01001099,  0.05098858,
       -0.12242872,  0.08092836, -0.06791194,  0.05861909, -0.11603323,
       -0.03153627,  0.09908666,  0.06579974,  0.03993439, -0.05210162,
        0.00666871, -0.22953184,  0.01598689,  0.03634018, -0.07705376,
       -0.14800063,  0.12090281, -0.13021603, -0.08185715,  0.1519484 ,
        0.08814736,  0.027516  ,  0.028056  ,  0.06988152,  0.00517484,
       -0.03458975,  0.00844377,  0.02469297, -0.00030825, -0.07978516,
       -0.0796921 ,  0.03141923, -0.06258724, -0.02241901,  0.06023757],
      dtype=float32)

In [22]:
from sklearn.metrics.pairwise import cosine_similarity
X = np.array(dev_claims_df['vector'].values.tolist())
y = np.array(evidence_df['vector'].values.tolist())
sim = cosine_similarity(X, y)
sim

array([[ 0.00117741,  0.24191558, -0.03670118, ...,  0.2770185 ,
         0.19545878, -0.09969829],
       [-0.19994286,  0.79901534, -0.48930073, ...,  0.870588  ,
         0.6441169 ,  0.07372354],
       [ 0.15423973,  0.07285927,  0.04803744, ...,  0.16585894,
         0.12644769,  0.05646985],
       ...,
       [-0.09713285,  0.15564387, -0.00675905, ...,  0.04100898,
         0.10649468,  0.00219995],
       [-0.00975218,  0.09400634, -0.2910451 , ...,  0.23731726,
         0.11471446,  0.17199133],
       [-0.00845153,  0.097124  , -0.12998559, ...,  0.2928345 ,
         0.16397814,  0.3564576 ]], dtype=float32)

In [23]:
for i in range(sim.shape[0]):
    print(np.where(sim[i]>0.7))

(array([  47847,   69090,   80646,   81037,   85519,   98593,  108925,
        144201,  148161,  163468,  163656,  164501,  169795,  179706,
        181500,  192479,  220223,  230320,  250017,  260583,  275430,
        279864,  282633,  293514,  349454,  358578,  374505,  382811,
        409221,  434774,  443311,  456796,  460668,  480899,  497068,
        501849,  558547,  572512,  585338,  597849,  599907,  600127,
        605361,  614499,  632706,  641060,  643464,  649294,  649584,
        679350,  684667,  697698,  713567,  716061,  718936,  744921,
        756198,  757863,  760144,  763705,  769999,  811839,  814661,
        819261,  825238,  844889,  857093,  866834,  872151,  910426,
        917387,  926163,  935211,  975241,  996254, 1023710, 1029971,
       1036628, 1044999, 1096974, 1131651, 1160482, 1162000, 1177471,
       1181118, 1182886]),)
(array([      1,       9,      21, ..., 1208816, 1208818, 1208824]),)
(array([], dtype=int64),)
(array([130492]),)
(array([  31748,   47501,   66438,  129342,  131731,  131765,  149290,
        178894,  199625,  233834,  274316,  325525,  340647,  346151,
        361423,  380586,  382316,  395191,  446869,  449403,  483254,
        499938,  525313,  529556,  544388,  556911,  572376,  592794,
        599644,  649652,  660135,  671426,  680290,  694231,  696389,
        701247,  794488,  799326,  824163,  837857,  843557,  857269,
        857312,  860547,  865679,  943183,  988105,  999513, 1023951,
       1055742, 1113630, 1160351, 1192029]),)
(array([      1,       5,       9, ..., 1208805, 1208816, 1208824]),)
(array([243209, 432823, 680837, 893173, 974798]),)
(array([ 323909,  670600, 1107462, 1136692]),)
(array([  18510,   53929,   54062,   64707,   76588,   77533,   82189,
         87603,  104305,  111492,  124206,  124522,  153273,  170018,
        183642,  198783,  206022,  214637,  236410,  241127,  266237,
        282591,  287577,  288298,  289231,  301922,  302651,  316760,
        320784,  321461,  334356,  336375,  340693,  348613,  363264,
        367348,  394692,  397833,  411356,  432228,  444300,  449860,
        480564,  499929,  510765,  514522,  524738,  541044,  547492,
        550906,  552546,  554261,  563330,  577889,  584694,  613119,
        622706,  678998,  682489,  688409,  742401,  744925,  752384,
        759620,  760148,  766109,  776769,  784880,  792347,  794529,
        795798,  797763,  813733,  819049,  828631,  834946,  883175,
        889375,  902004,  944763,  948965,  954628,  957603,  961475,
        967137,  988341,  999922, 1001239, 1002791, 1011723, 1020223,
       1022251, 1025067, 1026767, 1030842, 1032635, 1065747, 1080074,
       1088319, 1096990, 1111621, 1116346, 1123557, 1137257, 1157327,
       1167493, 1182904, 1196792, 1203650]),)
(array([   2012,    3685,    4552,    6518,   29018,   38025,   48561,
         56142,   61155,   69826,   72067,   80888,  126658,  133991,
        144009,  147346,  148321,  149215,  149926,  155949,  193786,
        199880,  207232,  227916,  237307,  250220,  274995,  282263,
        284688,  300436,  336714,  343565,  374792,  374889,  375094,
        390596,  398169,  399600,  400625,  401235,  403355,  405677,
        413471,  416805,  436236,  480970,  501124,  509435,  510433,
        512887,  524535,  592932,  604160,  615145,  618325,  623219,
        625615,  632264,  633651,  650655,  655708,  662703,  663686,
        670962,  688293,  738595,  803489,  805985,  809901,  817122,
        818219,  820269,  830707,  834386,  849368,  852853,  879137,
        890920,  897691,  906020,  908739,  909112,  974645,  994725,
       1045964, 1050982, 1057427, 1064133, 1072441, 1082944, 1083616,
       1097137, 1101203, 1110639, 1111025, 1119612, 1134011, 1135467,
       1168845, 1175571, 1187528, 1192336, 1205160, 1208280]),)
(array([], dtype=int64),)
(array([      1,       5,       9, ..., 1208822, 1208823, 1208824]),)
(array([      1,       9,      25, ..., 1208822, 1208823, 1208824]),)
(array([     25,      36,      58, ..., 1208799, 1208805, 1208824]),)
(array([      1,       9,      20, ..., 1208812, 1208816, 1208824]),)
(array([622812, 849364, 857536]),)
(array([  75422,  116675,  121920,  147671,  167613,  195709,  238503,
        350403,  431231,  448981,  471939,  476531,  508011,  545358,
        575574,  582638,  594928,  636447,  715864,  720079,  731810,
        753529,  788049,  800921,  849094,  849105,  906768,  940404,
        977792,  985889,  993111, 1027216, 1052187, 1080836, 1193645]),)
(array([1160483]),)
(array([   9905,   27046,   31972,   41116,   61281,   80245,   94554,
        111881,  112013,  131569,  150384,  154409,  154433,  163475,
        165399,  172532,  177064,  178161,  203484,  220886,  222766,
        231992,  250552,  253434,  260332,  266114,  270200,  306186,
        313896,  319695,  320274,  333817,  350797,  354459,  370940,
        376541,  396301,  412647,  412708,  416423,  426250,  430845,
        458492,  460062,  463227,  468356,  469370,  478014,  482108,
        486187,  494460,  501093,  506355,  520917,  529556,  533665,
        542145,  542295,  543838,  547668,  567582,  594232,  610129,
        612803,  623594,  640436,  663585,  680033,  698988,  713533,
        719866,  760561,  771897,  772957,  780229,  786106,  799361,
        800686,  824669,  843557,  848404,  850815,  875972,  876272,
        887631,  907279,  928548,  948824,  956346,  967158,  976165,
        998388, 1003754, 1017229, 1020998, 1038718, 1052400, 1074297,
       1093562, 1113630, 1118064, 1127607, 1134963, 1137895, 1158399,
       1159569, 1168299, 1182339, 1182580]),)
(array([], dtype=int64),)
(array([   1666,    1830,    2232, ..., 1203848, 1208427, 1208474]),)
(array([   8043,    8166,    9969,   10141,   10172,   10879,   13489,
         14421,   17043,   17644,   18092,   18378,   19135,   19618,
         20677,   22369,   23270,   25099,   26055,   27292,   27791,
         29501,   31427,   38032,   39138,   40884,   43769,   46137,
         47123,   47586,   48663,   48954,   51933,   53071,   54548,
         54965,   56089,   57414,   62149,   63046,   66547,   67038,
         67161,   67436,   70446,   78277,   81692,   83149,   84918,
         85136,   86631,   87173,   89011,   93249,   95105,   95317,
         96457,  103275,  103404,  104057,  111904,  112055,  113216,
        115441,  117870,  117958,  125613,  127198,  129435,  131265,
        132039,  132767,  132908,  134132,  135746,  138617,  139857,
        140970,  141096,  142607,  142854,  143901,  147676,  148002,
        148367,  148866,  149027,  151784,  155052,  157628,  158630,
        160063,  163412,  164587,  164896,  166614,  172395,  174620,
        178173,  178852,  180725,  183963,  186679,  188015,  188679,
        190771,  191562,  191830,  194295,  195348,  197291,  197412,
        199791,  200321,  205032,  205484,  205898,  208789,  209677,
        213558,  214842,  216125,  216812,  223423,  224068,  224634,
        228055,  228808,  231512,  233073,  235822,  237419,  237463,
        240343,  242139,  242326,  242433,  244023,  245346,  245507,
        245630,  245905,  247357,  247881,  249344,  253959,  255851,
        259077,  259701,  259754,  262616,  262618,  265526,  265752,
        265874,  267081,  273857,  274220,  275089,  277372,  277743,
        279130,  279211,  280724,  281313,  281515,  282969,  287308,
        288737,  289195,  291949,  296549,  298758,  300621,  302055,
        305090,  305297,  305421,  318535,  320969,  322329,  328334,
        328961,  329037,  330907,  332866,  333128,  337597,  339910,
        341792,  343420,  344595,  346543,  346611,  346949,  351157,
        351665,  351777,  353390,  354856,  355240,  356035,  358412,
        358674,  368554,  369901,  370807,  373934,  381507,  382611,
        386084,  388881,  393260,  394781,  397311,  398804,  401551,
        403269,  409745,  410196,  413274,  416882,  418952,  420735,
        421599,  425162,  425222,  425381,  426165,  428985,  429252,
        430816,  431498,  435579,  437837,  438768,  439740,  440308,
        440501,  440940,  440991,  443438,  444676,  447239,  448661,
        449670,  449836,  450403,  450441,  453926,  455434,  455963,
        458871,  459847,  460231,  460682,  464161,  468084,  469245,
        474187,  475653,  479325,  482450,  484094,  489860,  490000,
        490721,  492785,  492809,  496262,  496290,  500121,  506417,
        509554,  510094,  517912,  518547,  524836,  526568,  528271,
        529905,  531488,  534688,  535577,  536190,  536402,  542986,
        543788,  544000,  545258,  547275,  552915,  554178,  561925,
        563241,  568120,  570806,  572926,  573445,  573678,  580464,
        581777,  581860,  584725,  584784,  588493,  590266,  593490,
        599421,  601157,  602209,  602567,  605207,  606557,  606574,
        606674,  606989,  607029,  608703,  610233,  612830,  619527,
        624430,  629457,  631268,  639167,  646738,  653846,  654598,
        657324,  658795,  659305,  664209,  668322,  675166,  676652,
        681047,  681722,  684920,  685839,  686588,  689511,  691670,
        703078,  703695,  704246,  706805,  707331,  709745,  712242,
        713491,  716479,  718845,  721250,  722686,  723695,  724769,
        725440,  731979,  732345,  733415,  734288,  736606,  737032,
        741474,  742906,  743301,  743855,  748420,  753002,  759287,
        760855,  761435,  761925,  762770,  765995,  768651,  769688,
        771697,  776522,  778908,  779891,  780669,  785893,  787065,
        789180,  791045,  798880,  801260,  801367,  801648,  803997,
        804743,  805181,  808359,  808374,  810313,  813485,  822350,
        827568,  828643,  831329,  831943,  832619,  835890,  844643,
        845036,  850094,  850309,  852429,  853035,  853432,  855056,
        856263,  857642,  857924,  858811,  859129,  861518,  861760,
        864013,  864417,  865174,  866023,  866243,  867196,  868767,
        870755,  871520,  874386,  874627,  876970,  881455,  884206,
        884473,  887907,  888401,  891669,  893852,  898588,  900441,
        900765,  903427,  905215,  906081,  906435,  908852,  910251,
        910704,  913340,  913346,  914714,  915210,  915724,  916164,
        916725,  919506,  921226,  921950,  925069,  927331,  927505,
        933580,  934359,  942387,  942621,  944061,  947122,  947714,
        948124,  948944,  953757,  953908,  959077,  959321,  960560,
        962000,  963012,  963297,  965092,  968976,  969280,  970072,
        978201,  979318,  985089,  989322,  990882,  991885,  992162,
        995240,  995688,  997934,  999197,  999819, 1001832, 1003780,
       1006936, 1007851, 1008438, 1014342, 1015612, 1021048, 1026318,
       1027051, 1029382, 1030537, 1032412, 1032415, 1033607, 1034043,
       1035353, 1038339, 1039739, 1043343, 1044028, 1044641, 1048591,
       1050229, 1050246, 1050735, 1053244, 1056077, 1056989, 1059302,
       1065982, 1066097, 1070314, 1074492, 1076544, 1077617, 1084049,
       1084120, 1084659, 1085997, 1087202, 1087848, 1090711, 1091195,
       1096021, 1096119, 1099847, 1100532, 1100673, 1103282, 1105373,
       1108887, 1115704, 1116592, 1119731, 1119800, 1120513, 1122614,
       1125128, 1126245, 1129751, 1137618, 1137748, 1138412, 1139269,
       1141252, 1142557, 1146318, 1149153, 1149746, 1151336, 1152169,
       1152975, 1154177, 1157932, 1159178, 1159254, 1164631, 1164693,
       1167577, 1168734, 1171805, 1174807, 1175622, 1176008, 1176393,
       1177173, 1178681, 1179216, 1180260, 1183486, 1184706, 1186900,
       1186948, 1189571, 1189747, 1193691, 1194993, 1195333, 1199018,
       1202773, 1203691, 1205328, 1208010]),)
(array([], dtype=int64),)
(array([      1,       9,      20, ..., 1208822, 1208823, 1208824]),)
(array([      1,      25,      36, ..., 1208812, 1208816, 1208824]),)
(array([  98394,  371907,  613785,  649335,  666066,  669388,  893434,
       1083026]),)
(array([      5,      20,      23, ..., 1208805, 1208816, 1208824]),)
(array([     64,    8084,   13519,   15936,   16442,   27057,   30830,
         38996,   43568,   47575,   51238,   56082,   63203,   71651,
         80123,   83447,   90555,   93728,   96830,   97263,  103579,
        107995,  110354,  111831,  114618,  116185,  120221,  123859,
        126335,  130181,  132905,  134277,  135016,  140071,  140891,
        155006,  156089,  160708,  165685,  167129,  171372,  172955,
        176654,  177450,  183166,  185581,  185700,  193471,  194655,
        198082,  199823,  210363,  217079,  219631,  235136,  242159,
        246767,  251474,  255269,  255284,  258890,  260144,  261509,
        265626,  266662,  267955,  276289,  288212,  308212,  312281,
        327294,  328448,  329466,  330264,  336764,  337470,  338170,
        339731,  340852,  341275,  341876,  342386,  343062,  345723,
        353586,  365318,  371828,  372623,  374920,  389229,  389873,
        390884,  391057,  401692,  403797,  404748,  409016,  427047,
        431370,  434125,  434316,  438854,  443823,  445772,  447417,
        452289,  459441,  465707,  466204,  467730,  469984,  470861,
        480626,  484086,  484321,  490116,  498299,  522364,  524456,
        548541,  552256,  557648,  562390,  563457,  578552,  579464,
        583644,  584676,  585407,  586908,  588157,  595329,  626327,
        630207,  633471,  641037,  650781,  662689,  672373,  676358,
        677341,  679700,  684347,  689554,  695444,  696897,  699614,
        705236,  709795,  729270,  736101,  741504,  750565,  755684,
        758592,  758729,  758990,  761932,  765216,  768490,  775364,
        783453,  788461,  794928,  806126,  813409,  815739,  819080,
        822325,  826703,  830810,  831393,  831432,  832045,  834184,
        835456,  837530,  842685,  843806,  849721,  855299,  858656,
        861743,  861764,  862463,  862913,  864481,  868194,  869227,
        869337,  880278,  886824,  888612,  891290,  894576,  894980,
        896247,  900666,  903408,  908325,  911056,  922437,  923766,
        929713,  942135,  952313,  953562,  953919,  965812,  967596,
        970427,  975051,  982210,  982917,  990980,  991242,  993632,
        995618,  997161, 1008958, 1019046, 1021111, 1030014, 1046610,
       1055315, 1057024, 1063908, 1064443, 1065458, 1066569, 1071024,
       1076161, 1092693, 1093563, 1103522, 1109807, 1116066, 1120715,
       1125396, 1131230, 1133818, 1134328, 1137289, 1148459, 1156261,
       1158692, 1159969, 1160630, 1189957, 1191196, 1197582, 1199080,
       1200438, 1204652, 1204821]),)
(array([ 58709, 121173, 204810, 424251, 469061, 478880, 498314, 504952,
       591473, 689819, 771487, 807696, 903074, 910442]),)
(array([   2077,   33947,   80111,  116470,  131601,  178306,  255117,
        272181,  283074,  345561,  350914,  366110,  400746,  410145,
        456464,  472196,  485932,  499429,  504683,  529049,  543343,
        574490,  581126,  584456,  631423,  672194,  686897,  776703,
        791950,  808749,  819907,  883776,  902218,  929062,  929101,
        961952,  964856,  989772, 1015257, 1027867, 1034409, 1038880,
       1048496, 1071853, 1128756, 1188620, 1198243]),)
(array([], dtype=int64),)
(array([      1,       3,       5, ..., 1208822, 1208823, 1208824]),)
(array([  14983,   20522,   29735,   32025,   32256,   37768,   40113,
         41418,   42136,   51840,   53303,   55060,   57767,   59718,
         65220,   69898,   71029,   72248,   87639,   89125,   98087,
        110498,  116444,  135094,  136734,  141347,  151121,  151471,
        153540,  158574,  159348,  161577,  168360,  182224,  185180,
        195855,  195883,  199218,  203145,  211508,  215073,  219151,
        220859,  234907,  239996,  244358,  246952,  248599,  252929,
        258566,  263391,  285117,  286794,  287610,  295817,  301809,
        308629,  314022,  314092,  317232,  319332,  322129,  326752,
        334414,  350115,  350772,  356088,  357156,  357735,  363740,
        364928,  367907,  376060,  385766,  389209,  400635,  404348,
        406003,  406799,  408526,  409564,  423096,  425091,  434558,
        438864,  441566,  445637,  467287,  470711,  478058,  478551,
        481279,  488773,  490242,  491124,  493504,  499755,  500488,
        500508,  501554,  502771,  513636,  519912,  532270,  536484,
        536975,  540629,  542204,  542496,  542866,  544654,  546687,
        546968,  551187,  552058,  561422,  563459,  570183,  571378,
        572010,  577389,  581821,  591811,  592615,  595369,  598551,
        607448,  608109,  611843,  613579,  623599,  624537,  625271,
        625611,  628611,  630872,  634544,  636612,  643041,  645981,
        650338,  657691,  662404,  665412,  667200,  671781,  678962,
        679534,  682187,  686287,  688827,  692187,  700311,  706760,
        713162,  714996,  721325,  730346,  738712,  741940,  742618,
        747432,  750472,  759723,  771655,  773471,  776452,  777338,
        789768,  790747,  793577,  793918,  798230,  804178,  813572,
        815691,  818684,  825679,  836667,  842765,  845189,  854880,
        858618,  859697,  861200,  873845,  882863,  887501,  896110,
        899193,  902385,  903016,  917346,  924906,  929468,  932669,
        942834,  963856,  977831,  977841,  989161,  989665,  990721,
       1000256, 1004677, 1016815, 1030359, 1031226, 1043785, 1049981,
       1053751, 1057152, 1070959, 1080002, 1090472, 1092331, 1094747,
       1096428, 1098557, 1102187, 1106482, 1106776, 1116314, 1123366,
       1126784, 1126936, 1127116, 1128939, 1130857, 1144932, 1148901,
       1150273, 1152145, 1164059, 1165253, 1177569, 1178893, 1178947,
       1181044, 1186539, 1186955, 1192198, 1194900, 1208474]),)
(array([    177,     237,     278, ..., 1208526, 1208543, 1208711]),)
(array([      1,      20,      25, ..., 1208812, 1208816, 1208824]),)
(array([     25,      36,      58, ..., 1208807, 1208816, 1208824]),)
(array([], dtype=int64),)
(array([     36,      58,      61, ..., 1208766, 1208769, 1208775]),)
(array([      5,      25,      36, ..., 1208805, 1208816, 1208824]),)
(array([ 601172, 1006918]),)
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([  12286,   38154,   63755,   69839,   91425,  138130,  180457,
        197104,  207544,  261700,  304699,  354368,  396832,  440213,
        533387,  577061,  599273,  614130,  617951,  623058,  645532,
        675735,  681407,  749138,  786890,  802131,  836424,  848846,
        967423,  971601, 1160446]),)
(array([ 533044, 1117130]),)
(array([  47042, 1191885]),)
(array([ 360132,  760152, 1057017]),)
(array([    156,     158,     289, ..., 1208496, 1208648, 1208696]),)
(array([      1,       3,       5, ..., 1208822, 1208823, 1208824]),)
(array([     95,     106,     139, ..., 1208714, 1208725, 1208750]),)
(array([      1,      20,      25, ..., 1208805, 1208812, 1208824]),)
(array([      9,      11,      25, ..., 1208822, 1208823, 1208824]),)
(array([   1791,    5760,   13647,   14940,   16654,   16804,   17006,
         17994,   18270,   18364,   30991,   39430,   39634,   41533,
         42833,   44883,   56938,   57127,   57935,   61341,   74547,
         76536,   76588,   76864,   78559,   85981,   88688,   91194,
         91615,   92993,   94498,   94728,   97391,  105701,  106006,
        108867,  109565,  112259,  113052,  116240,  122611,  122690,
        122914,  124827,  131161,  131607,  132294,  133593,  135324,
        137564,  140322,  143808,  144160,  145199,  145780,  146655,
        147543,  148312,  148898,  150422,  152697,  153753,  157676,
        158273,  161370,  173242,  174874,  176060,  176931,  185797,
        187776,  188319,  190131,  193650,  194460,  194764,  200949,
        201410,  202558,  208645,  209771,  212386,  212481,  216221,
        216942,  226467,  229745,  233362,  238417,  242620,  245558,
        246585,  247665,  248989,  250766,  253126,  257244,  257691,